version: '3'

services:

  master:
    image: nkooinga/jmeter-docker/jmeter-master/dockerfile
    container_name: master
    tty: true
    hostname: master
    networks:
      - stcperf
  slave:
    image: nkooinga/jmeter-docker/jmeter-server/dockerfile
    tty: true
    networks:
      - stcperf

networks:
  stcperf:
    driver: bridge
